# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName("mainWin")
        mainWin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 260, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(570, 260, 72, 15))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 360, 801, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stopbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stopbut.setMaximumSize(QtCore.QSize(100, 30))
        self.stopbut.setObjectName("stopbut")
        self.gridLayout_3.addWidget(self.stopbut, 0, 1, 1, 1)
        self.initbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.initbut.setMaximumSize(QtCore.QSize(100, 30))
        self.initbut.setObjectName("initbut")
        self.gridLayout_3.addWidget(self.initbut, 0, 0, 1, 1)
        self.unknowbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.unknowbut.setMaximumSize(QtCore.QSize(100, 30))
        self.unknowbut.setObjectName("unknowbut")
        self.gridLayout_3.addWidget(self.unknowbut, 1, 0, 1, 1)
        self.exitbut = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exitbut.setMaximumSize(QtCore.QSize(100, 30))
        self.exitbut.setObjectName("exitbut")
        self.gridLayout_3.addWidget(self.exitbut, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(170, 100, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(590, 90, 20, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(270, 70, 251, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(270, 260, 251, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.status_light0 = QtWidgets.QLabel(self.centralwidget)
        self.status_light0.setGeometry(QtCore.QRect(10, 70, 72, 15))
        self.status_light0.setObjectName("status_light0")
        self.status_light1 = QtWidgets.QLabel(self.centralwidget)
        self.status_light1.setGeometry(QtCore.QRect(10, 260, 72, 15))
        self.status_light1.setObjectName("status_light1")
        self.status_light2 = QtWidgets.QLabel(self.centralwidget)
        self.status_light2.setGeometry(QtCore.QRect(710, 70, 72, 15))
        self.status_light2.setObjectName("status_light2")
        self.status_light3 = QtWidgets.QLabel(self.centralwidget)
        self.status_light3.setGeometry(QtCore.QRect(710, 260, 72, 15))
        self.status_light3.setObjectName("status_light3")
        self.edge = QtWidgets.QLineEdit(self.centralwidget)
        self.edge.setGeometry(QtCore.QRect(370, 50, 30, 20))
        self.edge.setObjectName("edge")
        mainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        mainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWin)
        self.statusbar.setObjectName("statusbar")
        mainWin.setStatusBar(self.statusbar)

        self.retranslateUi(mainWin)
        QtCore.QMetaObject.connectSlotsByName(mainWin)

    def retranslateUi(self, mainWin):
        _translate = QtCore.QCoreApplication.translate
        mainWin.setWindowTitle(_translate("mainWin", "MainWindow"))
        self.label.setText(_translate("mainWin", "TextLabel"))
        self.label_2.setText(_translate("mainWin", "TextLabel"))
        self.label_3.setText(_translate("mainWin", "TextLabel"))
        self.label_4.setText(_translate("mainWin", "TextLabel"))
        self.stopbut.setText(_translate("mainWin", "停止"))
        self.initbut.setText(_translate("mainWin", "初始化路由"))
        self.unknowbut.setText(_translate("mainWin", "PushButton"))
        self.exitbut.setText(_translate("mainWin", "退出"))
        self.status_light0.setText(_translate("mainWin", "TextLabel"))
        self.status_light1.setText(_translate("mainWin", "TextLabel"))
        self.status_light2.setText(_translate("mainWin", "TextLabel"))
        self.status_light3.setText(_translate("mainWin", "TextLabel"))
        self.edge.setPlaceholderText(_translate("mainWin", "1"))

